#![cfg(not(doctest))]

use core::panic;

use darling::{FromDeriveInput, FromField, FromMeta};
use proc_macro::TokenStream;
use quote::{ToTokens, quote};
use syn::{
    Data, DataStruct, DeriveInput, Expr, Fields, GenericArgument, Ident, PathArguments, Type,
    parse_str, parse2,
};

extern crate proc_macro;

/// Implements `From` trait for structs. This macro is designed to be used to
/// convert `graphql_client` library's autogenerated struct data into project's
/// struct.
///
/// It has `names` attribute on a struct level, which is a list of types that
/// will be converted. It is required.
///
/// It also has `from_name`, `recursive_into`, `skip` attributes on a field
/// level. `from_name` attribute is used to specify the name of the field in the
/// source struct, if the name of the field in the source struct is different
/// from the name of the field in the target struct. `recursive_into` attribute
/// is used to specify whether the field should be converted recursively by a
/// custom type's `From` implementation. `skip` attribute is used to specify
/// whether the field should be skipped. When more than one element is present
/// in the `names` attribute, each element will share the field level
/// attributes. All field level attributes are optional.
///
/// NOTE : this macro relies on lossy casting, `as _` when necessary, but this
/// is not an issue. It is because the integrity of data is solely upon the
/// project's struct, so data loss shall never happen. `graphql_client` library
/// and graphql's interpretes all number types as i64 at its code autogen, hence
/// it is necessary to force-cast.
///
/// LIMITATIONS : `graphql_client` library does not autogenerate tuple types as
/// response data. So for practical reason, this macro does not support tuple
/// types.
///
/// # Panics
/// Panics only occur in compile time, never in runtime. This macro panics when
/// inputs are incorrect. When you fail to use this macro, please run with -Z
/// macro-backtrace for more info. Since macro expansion occurs during
/// compilatione.
///
/// # Examples
/// ```no_run
/// use graphql_client::GraphQLQuery;
/// use async_graphql::SimpleObject;
///
/// #[derive(GraphQLQuery)]
/// #[graphql(
///     schema_path = "src/graphql/client/schema/schema.graphql",
///     query_path = "src/graphql/client/schema/example_raw_events.graphql",
///     response_derives = "Clone, Default, PartialEq"
/// )]
/// pub struct ExampleRawEvents;
///
/// #[derive(SimpleObject, ConvertGraphQLEdgesNode)]
/// #[graphql_client_type(names = [example_raw_events::ExampleRawEventsExampleRawEventsEdgesNode, network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEvent])]
/// struct ExampleRawEvent {
///     time: DateTime,
///     orig_port: Option<u16>,
///     proto: u8,
///     start_time: i64,
///     service: String,
///     resp_pkts: u64,
///     ttl: Vec<i32>,
///     filenames: Vec<String>,
///     #[graphql_client_type(from_name = "ja3_s")]
///     ja3s: String,
///     #[graphql_client_type(skip = true)]
///     some_field: String,
///     #[graphql_client_type(recursive_into = true)]
///     details: Vec<ExampleRawEventDetail>,
/// }
///
/// #[graphql_client_type(names = [example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetails, network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetails])]
/// pub struct ExampleRawEventDetail {
///     pub protocol: String,
///     pub pps: Option<f64>,
///     #[graphql_client_type(recursive_into = true)]
///     pub link: Vec<ExampleRawEventHelpLink>,
/// }
///
/// #[graphql_client_type(names = [example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetailsLink, network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetailsLink])]
/// pub struct ExampleRawEventHelpLink {
///     pub url: String,
/// }
///```
///
/// Above code expands to below.
/// ```no_run
/// impl From<example_raw_events::ExampleRawEventsExampleRawEventsEdgesNode> for ExampleRawEvent {
///     fn from(node: example_raw_events::ExampleRawEventsExampleRawEventsEdgesNode) -> Self {
///         Self {
///             time: node.time,
///             orig_port: node.orig_port.map(|x| x as _),
///             proto: node.proto as _,
///             start_time: node.start_time as _,
///             service: node.service,
///             resp_pkts: node.resp_pkts,
///             ttl: node.ttl.into_iter().map(|x| x as _).collect(),
///             filenames: node.filenames,
///             ja3s: node.ja3_s,
///             details: node.details.into_iter().map(|x| x.into()).collect(),
///         }
///     }
/// }
///
/// impl From<network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEvent> for ExampleRawEvent {
///     fn from(node: network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEvent) -> Self {
///         Self {
///             time: node.time,
///             orig_port: node.orig_port.map(|x| x as _),
///             proto: node.proto as _,
///             start_time: node.start_time as _,
///             service: node.service as _,
///             resp_pkts: node.resp_pkts as _,
///             ttl: node.ttl.into_iter().map(|x| x as _).collect(),
///             filenames: node.filenames,
///             ja3s: node.ja3_s,
///             details: node.details.into_iter().map(|x| x.into()).collect(),
///         }
///     }
/// }
///
/// impl From<example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetails> for ExampleRawEventDetail {
///     fn from(node: example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetails) -> Self {
///         Self {
///             protocol: node.protocol,
///             pps: node.pps,
///             link: node.link.into_iter().map(|x| x.into()).collect(),
///         }
///     }
/// }
///
/// impl From<network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetails> for ExampleRawEventDetail {
///     fn from(node: network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetails) -> Self {
///         Self {
///             protocol: node.protocol,
///             pps: node.pps,
///             link: node.link.into_iter().map(|x| x.into()).collect(),
///         }
///     }
/// }
///
/// impl From<example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetailsLink> for ExampleRawEventHelpLink {
///     fn from(node: example_raw_events::ExampleRawEventsExampleRawEventsEdgesNodeDetailsLink) -> Self {
///         Self {
///             url: node.url,
///         }
///     }
/// }
///
/// impl From<network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetailsLink> for ExampleRawEventHelpLink {
///     fn from(node: network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnExampleRawEventDetailsLink) -> Self {
///         Self {
///             url: node.url,
///         }
///     }
/// }
///
/// ```
#[proc_macro_derive(ConvertGraphQLEdgesNode, attributes(graphql_client_type))]
pub fn derive_from_graphql_client_autogen(input: TokenStream) -> TokenStream {
    match derive_from_graphql_client_autogen_2(input.clone().into()) {
        Ok(result) => result.into(),
        Err(e) => panic!("ConvertGraphQLEdgesNode macro is not correctly used for {input:?}: {e}"),
    }
}

#[derive(FromDeriveInput)]
#[darling(attributes(graphql_client_type))]
struct FromGraphQlAutogenStructAttrs {
    names: GraphQlClientTypes,
}

struct GraphQlClientTypes(Vec<Type>);

impl FromMeta for GraphQlClientTypes {
    fn from_expr(expr: &Expr) -> darling::Result<Self> {
        match expr {
            Expr::Array(array) => array
                .elems
                .iter()
                .map(|expr| {
                    parse2(expr.to_token_stream())
                        .map_err(|err| darling::Error::from(err).with_span(expr))
                })
                .collect::<darling::Result<Vec<_>>>()
                .map(Self),
            Expr::Group(group) => Self::from_expr(&group.expr),
            Expr::Paren(paren) => Self::from_expr(&paren.expr),
            _ => Err(darling::Error::unexpected_expr_type(expr)),
        }
    }
}

#[derive(FromField)]
#[darling(attributes(graphql_client_type))]
struct GraphQlAutogenFieldAttrs {
    #[darling(default)]
    pub from_name: String,
    #[darling(default)]
    pub recursive_into: bool,
    #[darling(default)]
    pub skip: bool,
}

#[allow(clippy::too_many_lines)]
fn derive_from_graphql_client_autogen_2(
    item: proc_macro2::TokenStream,
) -> darling::Result<proc_macro2::TokenStream> {
    let ast: DeriveInput = parse2(item)?;

    let FromGraphQlAutogenStructAttrs {
        names: GraphQlClientTypes(names),
    } = FromGraphQlAutogenStructAttrs::from_derive_input(&ast)?;

    let struct_ident = &ast.ident;

    let Data::Struct(DataStruct { fields, .. }) = &ast.data else {
        return Err(darling::Error::custom(
            "`ConvertGraphQLEdgesNode` can only be derived for structs",
        )
        .with_span(struct_ident));
    };

    let Fields::Named(named_fields) = fields else {
        return Err(darling::Error::custom(
            "Structs that derive `ConvertGraphQLEdgesNode` should only have named fields",
        )
        .with_span(struct_ident));
    };

    let field_conversions = named_fields
        .named
        .iter()
        .map(graphql_field_conversion)
        .collect::<darling::Result<Vec<_>>>()?;

    let implementations = names
        .into_iter()
        .map(|name| {
            quote! {
                impl From<#name> for #struct_ident {
                    fn from(node: #name) -> Self {
                        Self {
                            #( #field_conversions )*
                        }
                    }
                }
            }
        })
        .collect::<Vec<_>>();

    Ok(quote! {
        #(#implementations)*
    })
}

fn graphql_field_conversion(field: &syn::Field) -> darling::Result<proc_macro2::TokenStream> {
    let GraphQlAutogenFieldAttrs {
        from_name,
        recursive_into,
        skip,
    } = GraphQlAutogenFieldAttrs::from_field(field)?;

    if skip {
        return Ok(quote! {});
    }

    let Some(to_field_name) = &field.ident else {
        return Err(darling::Error::custom(
            "Fields converted by `ConvertGraphQLEdgesNode` should be named",
        )
        .with_span(field));
    };
    let from_field_name = resolve_from_field_name(&from_name, to_field_name, field)?;
    let field_type = &field.ty;

    let (segment_type, cast_style) = segment_type_and_cast_style(field_type, recursive_into)
        .map_err(|err| err.with_span(field))?;

    Ok(match (segment_type, cast_style) {
        (_, CastStyle::None) => {
            quote! {
                #to_field_name: node.#from_field_name,
            }
        }
        (SegmentType::Vec, CastStyle::As) => {
            quote! {
                #to_field_name: node.#from_field_name.into_iter().map(|x| x as _).collect(),
            }
        }
        (SegmentType::Option, CastStyle::As) => {
            quote! {
                #to_field_name: node.#from_field_name.map(|x| x as _),
            }
        }
        (SegmentType::Other, CastStyle::As) => {
            quote! {
                #to_field_name: node.#from_field_name as _,
            }
        }
        (SegmentType::Vec, CastStyle::Into) => {
            quote! {
                #to_field_name: node.#from_field_name.into_iter().map(|x| x.into()).collect(),
            }
        }
        (SegmentType::VecVec, CastStyle::As) => {
            quote! {
                #to_field_name: node.#from_field_name
                    .into_iter()
                    .map(|inner| inner.into_iter().map(|x| x as _).collect())
                    .collect(),
            }
        }
        (SegmentType::VecVec, CastStyle::Into) => {
            quote! {
                #to_field_name: node.#from_field_name
                    .into_iter()
                    .map(|inner| inner.into_iter().map(|x| x.into()).collect())
                    .collect(),
            }
        }
        (SegmentType::Option, CastStyle::Into) => {
            quote! {
                #to_field_name: node.#from_field_name.map(|x| x.into()),
            }
        }
        (SegmentType::Other, CastStyle::Into) => {
            quote! {
                #to_field_name: node.#from_field_name.into(),
            }
        }
    })
}

fn resolve_from_field_name(
    from_name: &str,
    field_name: &Ident,
    field: &syn::Field,
) -> darling::Result<Ident> {
    if from_name.is_empty() {
        Ok(field_name.clone())
    } else {
        parse_str::<Ident>(from_name).map_err(|err| {
            darling::Error::from(err)
                .with_span(field)
                .at(format!(r#"from_name = "{from_name}""#))
        })
    }
}

#[derive(PartialEq)]
enum SegmentType {
    Other,
    Vec,
    VecVec,
    Option,
}

#[derive(PartialEq)]
enum CastStyle {
    None,
    As,
    Into,
}

fn segment_type_and_cast_style(
    ty: &Type,
    recursive_into: bool,
) -> darling::Result<(SegmentType, CastStyle)> {
    if let Type::Path(type_path) = ty
        && let Some(segment) = type_path.path.segments.last()
    {
        if segment.ident == "Vec" {
            if let PathArguments::AngleBracketed(vec_element_type_arg) = &segment.arguments {
                for arg in &vec_element_type_arg.args {
                    if let GenericArgument::Type(el_type) = arg {
                        if let Some(inner_type) = vec_vec_inner_type(el_type) {
                            return Ok((
                                SegmentType::VecVec,
                                cast_style(inner_type, recursive_into)?,
                            ));
                        }
                        return Ok((SegmentType::Vec, cast_style(el_type, recursive_into)?));
                    }
                }
            }
        } else if segment.ident == "Option" {
            if let PathArguments::AngleBracketed(option_element_type_arg) = &segment.arguments {
                for arg in &option_element_type_arg.args {
                    if let GenericArgument::Type(el_type) = arg {
                        return Ok((SegmentType::Option, cast_style(el_type, recursive_into)?));
                    }
                }
            }
        } else {
            return Ok((SegmentType::Other, cast_style(ty, recursive_into)?));
        }
    }
    Ok((SegmentType::Other, cast_style(ty, recursive_into)?))
}

fn cast_style(field_type: &Type, recursive_into: bool) -> darling::Result<CastStyle> {
    if is_target_of_safe_to_i64_cast(field_type) {
        if recursive_into {
            return Err(darling::Error::custom(format!(
                "inappropriate use of `recursive_into`. Please remove `recursive_into` attribute on a field with `{}`",
                field_type.to_token_stream()
            )));
        }
        Ok(CastStyle::As)
    } else if recursive_into {
        Ok(CastStyle::Into)
    } else {
        Ok(CastStyle::None)
    }
}

static SAFE_TO_I64_TYPES: [&str; 5] = ["u8", "u16", "i8", "i16", "i32"];

fn is_target_of_safe_to_i64_cast(ty: &Type) -> bool {
    let type_token = ty.to_token_stream().to_string();
    SAFE_TO_I64_TYPES.contains(&type_token.as_str())
}

fn vec_vec_inner_type(ty: &Type) -> Option<&Type> {
    extract_vec_inner_type(ty)
}

fn extract_vec_inner_type(ty: &Type) -> Option<&Type> {
    if let Type::Path(type_path) = ty
        && let Some(segment) = type_path.path.segments.last()
        && segment.ident == "Vec"
        && let PathArguments::AngleBracketed(args) = &segment.arguments
    {
        for arg in &args.args {
            if let GenericArgument::Type(inner_ty) = arg {
                return Some(inner_ty);
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn graphql_client_types_parse_array_syntax() {
        let expr: Expr = syn::parse_quote!([foo::Bar, baz::Qux]);

        let types = GraphQlClientTypes::from_expr(&expr).expect("array syntax should parse");

        assert_eq!(types.0.len(), 2);
        assert_eq!(types.0[0].to_token_stream().to_string(), "foo :: Bar");
        assert_eq!(types.0[1].to_token_stream().to_string(), "baz :: Qux");
    }

    #[test]
    fn graphql_client_types_parse_parenthesized_array_syntax() {
        let expr: Expr = syn::parse_quote!(([foo::Bar]));

        let types =
            GraphQlClientTypes::from_expr(&expr).expect("parenthesized array syntax should parse");

        assert_eq!(types.0.len(), 1);
        assert_eq!(types.0[0].to_token_stream().to_string(), "foo :: Bar");
    }

    #[test]
    fn graphql_client_types_reject_non_array_syntax() {
        let expr: Expr = syn::parse_quote!(foo::Bar);

        assert!(GraphQlClientTypes::from_expr(&expr).is_err());
    }

    #[test]
    fn field_attrs_default_to_disabled_flags() {
        let field: syn::Field = syn::parse_quote!(value: String);

        let attrs = GraphQlAutogenFieldAttrs::from_field(&field).expect("field should parse");

        assert!(attrs.from_name.is_empty());
        assert!(!attrs.recursive_into);
        assert!(!attrs.skip);
    }

    #[test]
    fn field_attrs_parse_existing_syntax() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(from_name = "source", recursive_into = true, skip = true)]
            value: String
        );

        let attrs = GraphQlAutogenFieldAttrs::from_field(&field).expect("field should parse");

        assert_eq!(attrs.from_name, "source");
        assert!(attrs.recursive_into);
        assert!(attrs.skip);
    }

    #[test]
    fn field_conversion_uses_from_name() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(from_name = "source")]
            value: String
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert_eq!(conversion.to_string(), "value : node . source ,");
    }

    #[test]
    fn field_conversion_skips_fields() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(skip = true)]
            value: String
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert!(conversion.is_empty());
    }

    #[test]
    fn recursive_into_uses_into_for_plain_fields() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(recursive_into = true)]
            detail: Detail
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert_eq!(conversion.to_string(), "detail : node . detail . into () ,");
    }

    #[test]
    fn recursive_into_uses_into_for_option_fields() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(recursive_into = true)]
            detail: Option<Detail>
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert_eq!(
            conversion.to_string(),
            "detail : node . detail . map (| x | x . into ()) ,"
        );
    }

    #[test]
    fn recursive_into_uses_into_for_vec_fields() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(recursive_into = true)]
            details: Vec<Detail>
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert_eq!(
            conversion.to_string(),
            "details : node . details . into_iter () . map (| x | x . into ()) . collect () ,"
        );
    }

    #[test]
    fn recursive_into_uses_into_for_nested_vec_fields() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(recursive_into = true)]
            details: Vec<Vec<Detail>>
        );

        let conversion = graphql_field_conversion(&field).expect("field should convert");

        assert_eq!(
            conversion.to_string(),
            "details : node . details . into_iter () . map (| inner | inner . into_iter () . map (| x | x . into ()) . collect ()) . collect () ,"
        );
    }

    #[test]
    fn safe_integer_fields_use_as_casts() {
        let u8_field: syn::Field = syn::parse_quote!(value: u8);
        let u16_field: syn::Field = syn::parse_quote!(value: u16);
        let i8_field: syn::Field = syn::parse_quote!(value: i8);
        let i16_field: syn::Field = syn::parse_quote!(value: i16);
        let i32_field: syn::Field = syn::parse_quote!(value: i32);

        assert_eq!(
            graphql_field_conversion(&u8_field)
                .expect("u8 field should convert")
                .to_string(),
            "value : node . value as _ ,"
        );
        assert_eq!(
            graphql_field_conversion(&u16_field)
                .expect("u16 field should convert")
                .to_string(),
            "value : node . value as _ ,"
        );
        assert_eq!(
            graphql_field_conversion(&i8_field)
                .expect("i8 field should convert")
                .to_string(),
            "value : node . value as _ ,"
        );
        assert_eq!(
            graphql_field_conversion(&i16_field)
                .expect("i16 field should convert")
                .to_string(),
            "value : node . value as _ ,"
        );
        assert_eq!(
            graphql_field_conversion(&i32_field)
                .expect("i32 field should convert")
                .to_string(),
            "value : node . value as _ ,"
        );
    }

    #[test]
    fn safe_integer_container_fields_use_as_casts() {
        let vec_field: syn::Field = syn::parse_quote!(value: Vec<u8>);
        let nested_vec_field: syn::Field = syn::parse_quote!(value: Vec<Vec<u16>>);
        let option_field: syn::Field = syn::parse_quote!(value: Option<i32>);

        assert_eq!(
            graphql_field_conversion(&vec_field)
                .expect("Vec integer field should convert")
                .to_string(),
            "value : node . value . into_iter () . map (| x | x as _) . collect () ,"
        );
        assert_eq!(
            graphql_field_conversion(&nested_vec_field)
                .expect("nested Vec integer field should convert")
                .to_string(),
            "value : node . value . into_iter () . map (| inner | inner . into_iter () . map (| x | x as _) . collect ()) . collect () ,"
        );
        assert_eq!(
            graphql_field_conversion(&option_field)
                .expect("Option integer field should convert")
                .to_string(),
            "value : node . value . map (| x | x as _) ,"
        );
    }

    #[test]
    fn from_name_rejects_invalid_ident() {
        let field: syn::Field = syn::parse_quote!(
            #[graphql_client_type(from_name = "not-valid")]
            value: String
        );

        let err = graphql_field_conversion(&field).expect_err("invalid from_name should fail");

        assert!(err.to_string().contains("from_name"));
    }

    #[test]
    fn derive_generates_from_impl_for_named_struct() {
        let item = quote! {
            #[graphql_client_type(names = [source::Node])]
            struct Target {
                value: String,
            }
        };

        let generated = derive_from_graphql_client_autogen_2(item)
            .expect("named struct should generate conversion");
        let generated = generated.to_string();

        assert!(generated.contains("impl From < source :: Node > for Target"));
        assert!(generated.contains("value : node . value"));
    }

    #[test]
    fn derive_generates_from_impl_for_each_client_type() {
        let item = quote! {
            #[graphql_client_type(names = [source::Node, other::Node])]
            struct Target {
                value: String,
            }
        };

        let generated = derive_from_graphql_client_autogen_2(item)
            .expect("named struct should generate conversions");
        let generated = generated.to_string();

        assert_eq!(generated.matches("impl From <").count(), 2);
        assert!(generated.contains("impl From < source :: Node > for Target"));
        assert!(generated.contains("impl From < other :: Node > for Target"));
    }

    #[test]
    fn derive_rejects_tuple_structs() {
        let item = quote! {
            #[graphql_client_type(names = [source::Node])]
            struct Target(String);
        };

        let err = derive_from_graphql_client_autogen_2(item).expect_err("tuple struct should fail");

        assert!(err.to_string().contains("named fields"));
    }

    #[test]
    fn derive_rejects_enums() {
        let item = quote! {
            #[graphql_client_type(names = [source::Node])]
            enum Target {
                Value,
            }
        };

        let err = derive_from_graphql_client_autogen_2(item).expect_err("enum should fail");

        assert!(err.to_string().contains("only be derived for structs"));
    }

    #[test]
    fn recursive_into_is_rejected_for_casted_integer_types() {
        let ty: Type = syn::parse_quote!(u8);

        assert!(segment_type_and_cast_style(&ty, true).is_err());
    }
}
